# YOLO Evaluation Configuration

# Paths
paths:
  # COCO dataset paths
  coco_dataset:
    train_images: "/ssd_4TB/divake/Vision_LSF/data/COCO/train2014"
    val_images: "/ssd_4TB/divake/Vision_LSF/data/COCO/val2014"
    train_annotations: "/ssd_4TB/divake/Vision_LSF/data/COCO/annotations/instances_train2014.json"
    val_annotations: "/ssd_4TB/divake/Vision_LSF/data/COCO/annotations/instances_val2014.json"
  
  # Output directory for evaluation results
  output_dir: "/ssd_4TB/divake/Vision_LSF/yolo11/yolo11_eval_results"

# Model configuration
model:
  name: "yolo11n.pt"  # Model to evaluate
  device: "cuda"      # Use "cuda" or "cpu"
  conf_threshold: 0.25  # Confidence threshold for predictions
  iou_threshold: 0.45   # IoU threshold for NMS

# Cache configuration
cache:
  dir: 'yolo11_cache'   # Directory to store cache files
  cache_logits: true    # Whether to cache raw model outputs (logits) for conformal prediction
  logits_to_extract: ['probs', 'conf', 'cls']  # Types of logits to extract and cache

# Evaluation parameters
evaluation:
  # Dataset split to use ('train' or 'val')
  dataset_split: "val"
  
  # IoU threshold for matching predictions with ground truth
  match_iou_threshold: 0.5
  
  # Set to true to evaluate on all images, false for specific images
  eval_full_dataset: true
  
  # Maximum number of images to evaluate (null for all, or specify a number for limit)
  max_images: null
  
  # Specific image filenames to evaluate (if eval_full_dataset is false)
  specific_images:
    - "000000000139.jpg"
    - "000000000285.jpg"
    - "000000000632.jpg"
    - "000000000724.jpg"
    - "000000000776.jpg"
  
  # Class mapping file (if needed to map between different class schemes)
  class_mapping_file: 1000

# Visualization settings
visualization:
  # Whether to create visualizations
  enabled: false
  
  # Save visualizations to disk
  save: false
  
  # Show visualizations interactively (set to false for headless environments)
  show: false
  
  # Whether to draw ground truth boxes
  draw_ground_truth: true
  
  # Whether to draw predicted boxes
  draw_predictions: true
  
  # Maximum number of images to visualize
  max_vis_images: 10
  
  # Colors for different types of boxes
  colors:
    ground_truth: [0, 255, 0]    # Green
    true_positive: [0, 255, 255]  # Cyan
    false_positive: [0, 0, 255]   # Red
    false_negative: [255, 0, 255]  # Magenta
  
  # Font settings
  font:
    scale: 0.5
    thickness: 1
    color: [255, 255, 255]  # White
  
  # Line thickness for bounding boxes
  box_thickness: 2

# Metrics to calculate
metrics:
  # Calculate overall metrics
  overall: true
  
  # Calculate per-class metrics
  per_class: true
  
  # Calculate precision-recall curve
  pr_curve: true
  
  # AP calculation
  ap_iou_thresholds: [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]
  
  # Save metrics as CSV
  save_csv: true 